/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "../../packages/ui/src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Semantic Colors (Dark Theme First)
        background: {
          DEFAULT: "rgb(var(--color-background))",
          elevated: "rgb(var(--color-background-elevated))",
          hover: "rgb(var(--color-background-hover))",
        },
        foreground: {
          DEFAULT: "rgb(var(--color-foreground))",
          muted: "rgb(var(--color-foreground-muted))",
          subtle: "rgb(var(--color-foreground-subtle))",
        },
        border: {
          DEFAULT: "rgb(var(--color-border))",
          hover: "rgb(var(--color-border-hover))",
          focus: "rgb(var(--color-border-focus))",
        },
        // Primary Color Scale
        primary: {
          50: "rgb(var(--color-primary-50))",
          100: "rgb(var(--color-primary-100))",
          200: "rgb(var(--color-primary-200))",
          300: "rgb(var(--color-primary-300))",
          400: "rgb(var(--color-primary-400))",
          500: "rgb(var(--color-primary-500))",
          600: "rgb(var(--color-primary-600))",
          700: "rgb(var(--color-primary-700))",
          800: "rgb(var(--color-primary-800))",
          900: "rgb(var(--color-primary-900))",
          950: "rgb(var(--color-primary-950))",
        },
        // Secondary Color Scale
        secondary: {
          50: "rgb(var(--color-secondary-50))",
          100: "rgb(var(--color-secondary-100))",
          200: "rgb(var(--color-secondary-200))",
          300: "rgb(var(--color-secondary-300))",
          400: "rgb(var(--color-secondary-400))",
          500: "rgb(var(--color-secondary-500))",
          600: "rgb(var(--color-secondary-600))",
          700: "rgb(var(--color-secondary-700))",
          800: "rgb(var(--color-secondary-800))",
          900: "rgb(var(--color-secondary-900))",
          950: "rgb(var(--color-secondary-950))",
        },
        // Success Color Scale
        success: {
          50: "rgb(var(--color-success-50))",
          100: "rgb(var(--color-success-100))",
          200: "rgb(var(--color-success-200))",
          300: "rgb(var(--color-success-300))",
          400: "rgb(var(--color-success-400))",
          500: "rgb(var(--color-success-500))",
          600: "rgb(var(--color-success-600))",
          700: "rgb(var(--color-success-700))",
          800: "rgb(var(--color-success-800))",
          900: "rgb(var(--color-success-900))",
          950: "rgb(var(--color-success-950))",
        },
        // Error Color Scale
        error: {
          50: "rgb(var(--color-error-50))",
          100: "rgb(var(--color-error-100))",
          200: "rgb(var(--color-error-200))",
          300: "rgb(var(--color-error-300))",
          400: "rgb(var(--color-error-400))",
          500: "rgb(var(--color-error-500))",
          600: "rgb(var(--color-error-600))",
          700: "rgb(var(--color-error-700))",
          800: "rgb(var(--color-error-800))",
          900: "rgb(var(--color-error-900))",
          950: "rgb(var(--color-error-950))",
        },
        // Warning Color Scale
        warning: {
          50: "rgb(var(--color-warning-50))",
          100: "rgb(var(--color-warning-100))",
          200: "rgb(var(--color-warning-200))",
          300: "rgb(var(--color-warning-300))",
          400: "rgb(var(--color-warning-400))",
          500: "rgb(var(--color-warning-500))",
          600: "rgb(var(--color-warning-600))",
          700: "rgb(var(--color-warning-700))",
          800: "rgb(var(--color-warning-800))",
          900: "rgb(var(--color-warning-900))",
          950: "rgb(var(--color-warning-950))",
        },
        // Info Color Scale
        info: {
          50: "rgb(var(--color-info-50))",
          100: "rgb(var(--color-info-100))",
          200: "rgb(var(--color-info-200))",
          300: "rgb(var(--color-info-300))",
          400: "rgb(var(--color-info-400))",
          500: "rgb(var(--color-info-500))",
          600: "rgb(var(--color-info-600))",
          700: "rgb(var(--color-info-700))",
          800: "rgb(var(--color-info-800))",
          900: "rgb(var(--color-info-900))",
          950: "rgb(var(--color-info-950))",
        },
        // Neutral Color Scale
        neutral: {
          0: "rgb(var(--color-neutral-0))",
          50: "rgb(var(--color-neutral-50))",
          100: "rgb(var(--color-neutral-100))",
          200: "rgb(var(--color-neutral-200))",
          300: "rgb(var(--color-neutral-300))",
          400: "rgb(var(--color-neutral-400))",
          500: "rgb(var(--color-neutral-500))",
          600: "rgb(var(--color-neutral-600))",
          700: "rgb(var(--color-neutral-700))",
          800: "rgb(var(--color-neutral-800))",
          900: "rgb(var(--color-neutral-900))",
          950: "rgb(var(--color-neutral-950))",
        },
      },
      spacing: {
        // Using CSS variables for spacing
        0: "var(--spacing-0)",
        1: "var(--spacing-1)",
        2: "var(--spacing-2)",
        3: "var(--spacing-3)",
        4: "var(--spacing-4)",
        5: "var(--spacing-5)",
        6: "var(--spacing-6)",
        8: "var(--spacing-8)",
        10: "var(--spacing-10)",
        12: "var(--spacing-12)",
        16: "var(--spacing-16)",
        20: "var(--spacing-20)",
        24: "var(--spacing-24)",
      },
      fontFamily: {
        sans: ["var(--font-family-sans)", "sans-serif"],
        brand: ["var(--font-family-brand)", "sans-serif"],
        mono: ["var(--font-family-mono)", "monospace"],
      },
      fontSize: {
        xs: ["var(--font-size-xs)", { lineHeight: "var(--line-height-tight)" }],
        sm: ["var(--font-size-sm)", { lineHeight: "var(--line-height-normal)" }],
        base: ["var(--font-size-base)", { lineHeight: "var(--line-height-normal)" }],
        lg: ["var(--font-size-lg)", { lineHeight: "var(--line-height-normal)" }],
        xl: ["var(--font-size-xl)", { lineHeight: "var(--line-height-normal)" }],
        "2xl": ["var(--font-size-2xl)", { lineHeight: "var(--line-height-tight)" }],
        "3xl": ["var(--font-size-3xl)", { lineHeight: "var(--line-height-tight)" }],
        "4xl": ["var(--font-size-4xl)", { lineHeight: "var(--line-height-tight)" }],
        "5xl": ["var(--font-size-5xl)", { lineHeight: "var(--line-height-tight)" }],
      },
      fontWeight: {
        light: "var(--font-weight-light)",
        normal: "var(--font-weight-normal)",
        medium: "var(--font-weight-medium)",
        semibold: "var(--font-weight-semibold)",
        bold: "var(--font-weight-bold)",
      },
      borderRadius: {
        none: "var(--radius-none)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
        full: "var(--radius-full)",
      },
      boxShadow: {
        xs: "var(--shadow-xs)",
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        xl: "var(--shadow-xl)",
        "2xl": "var(--shadow-2xl)",
      },
      transitionDuration: {
        fast: "var(--transition-fast)",
        base: "var(--transition-base)",
        slow: "var(--transition-slow)",
      },
      zIndex: {
        base: "var(--z-base)",
        dropdown: "var(--z-dropdown)",
        sticky: "var(--z-sticky)",
        fixed: "var(--z-fixed)",
        "modal-backdrop": "var(--z-modal-backdrop)",
        modal: "var(--z-modal)",
        popover: "var(--z-popover)",
        tooltip: "var(--z-tooltip)",
      },
      opacity: {
        0: "var(--opacity-0)",
        25: "var(--opacity-25)",
        50: "var(--opacity-50)",
        75: "var(--opacity-75)",
        100: "var(--opacity-100)",
      },
      screens: {
        xs: "0px",
        sm: "640px",
        md: "768px",
        lg: "1024px",
        xl: "1280px",
        "2xl": "1536px",
      },
      keyframes: {
        spin: {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
        ping: {
          '0%': { transform: 'scale(1)', opacity: '1' },
          '75%, 100%': { transform: 'scale(2)', opacity: '0' },
        },
        scan: {
          '0%': { transform: 'translateY(-100%)' },
          '50%': { transform: 'translateY(100%)' },
          '100%': { transform: 'translateY(-100%)' },
        },
        shimmer: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
      },
      animation: {
        'spin-slow': 'spin 20s linear infinite',
        'spin-very-slow': 'spin 60s linear infinite',
        'spin-reverse': 'spin 40s linear infinite reverse',
        'ping-slow': 'ping 5s cubic-bezier(0,0,0.2,1) infinite',
        'scan': 'scan 4s ease-in-out infinite',
        'shimmer': 'shimmer 2s infinite',
      },
    },
  },
  plugins: [],
};
